export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <script
          src="https://cdn.jsdelivr.net/npm/@iframe-resizer/child"
          type="text/javascript"
          async
        ></script>
      </head>
      <body>{children}</body>
    </html>
  );
}
